use zomato_db;

-- qustion 10 to 19 here 

-- 		10. find avg time of delivery of every rider

select rider_id , AVG(TIMESTAMPDIFF(MINUTE, o.order_time, d.delivery_time)) AS avg_delivery_time_mins
from orders as o
join deliveries as d
on o.order_id = d.order_id
where d.delivery_status = 'delivered'
group by rider_id;


-- 		11. calculate each restaurent's growth ratio  based on total number od deliverd orders since its joining 

select count(*) as no_of_orders,
r.restaurant_name 
from orders as o 
join restaurants as r
on o.restaurant_id = r.restaurant_id
group by restaurant_name
order by no_of_orders desc;


-- 		12. segmentatin of customers based on orders 

SELECT 
    customer_id,
    AVG(total_amount) AS avg_order_value,
    CASE 
        WHEN AVG(total_amount) > (SELECT AVG(total_amount) FROM orders) THEN 'Gold'
        WHEN AVG(total_amount) = (SELECT AVG(total_amount) FROM orders) THEN 'Neutral'
        ELSE 'Cheaper'
    END AS customer_segment
FROM orders
GROUP BY customer_id;


-- 		13. calculate each rider monthly salary based on 8% in each delivry


SELECT 
d.rider_id,DATE_FORMAT(o.order_date, '%m-%y') AS month,
SUM(total_amount) AS revenue,SUM(total_amount) * 0.08 AS riders_earning
FROM orders AS o
JOIN deliveries AS d 
ON o.order_id = d.order_id
GROUP BY 1, 2
ORDER BY 1, 2;


-- 		14. order frequncy per day of the week and identify the peak day for each restaurant

select * from (
select r.restaurant_name,
date_format(o.order_date,'%W') as day,
count(o.order_id) as total_orders,
rank() over(partition by r.restaurant_name order by count(o.order_id) desc) as rankk
from orders as o
join restaurants as r
on o.restaurant_id = r.restaurant_id
group by 1,2
order by 1,3 desc
) as t1
where rankk =1;


-- 		15. calculate the total revanue generated by eacch customer over all their orders

select customer_id , 
sum(total_amount) 
from orders 
group by 1;

-- 		16. identify the monthly total sales 

select 
date_format(order_date,'%m-%y'), 
sum(total_amount) 
from orders 
group by 1;

-- 		17. track the popularity of specific order items over time and identify seasonal demand spikes

select date_format(order_date,'%m-%y'), 
order_item , 
count(order_item) as freq 
from orders 
group by 1,2 
order by 1;

-- 		18. rank each city based on total revanue for last year 

select 
r.city ,
sum(total_amount) as total_revanue,
rank() over (order by sum(total_amount) desc) as city_rank
from orders as o 
join
restaurants as r
on o.restaurant_id = r.restaurant_id
group by 1;








